---
- name: Dev
  hosts: dev
  become: yes
  
  tasks:
  - name: Get user name
    become: false
    shell: whoami
    register: 

  - name: Install "Git"
    apt:
      name: git
      state: latest

  - name: Update "NodeJS" deb
    shell: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

  - name: Install "NodeJS"
    apt:
      name: nodejs
      state: latest

  - name: Install "pm2"
    npm: install pm2 -g

  - name: Download "App" from git
    git:
      repo: https://github.com/Eduardgur/WeightTrackerTst.git
      dest: "/home/eduardgu/WeightTrackerTst"

  - name: Install node packages
    shell: npm install
    args:
      chdir: "/home/eduardgu/WeightTrackerTst"

  # - name: Initialize DB
  #   shell: npm run initdb
  #   args:
  #     chdir: "/home/eduardgu/WeightTrackerTst"
      
  # - name: clear process
  #   shell: pm2 delete all
  #   ignore_errors: yes

  # - name: run application
  #   shell: pm2 start npm -- run dev && pm2 save && pm2 startup
  #   args:
  #     chdir: "/home/eduardgu/WeightTrackerTst"

   