---
- hosts: dev
  become: yes
  tasks:
    - name: install git
      apt:
        name: git
        state: latest

    - name: update nodejs/npm deb
      ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

    - name: install nodejs/npm
      apt:
        name: nodejs
        state: present

    - name: install pm2
      shell: npm install pm2 -g

    - name: Download app from git
      ansible.builtin.git:
        repo: https://github.com/Eduardgur/WeightTrackerTst.git
        dest: "~/WeightTrackerTst"

    - name: install node dependecies
      shell: npm install
      args:
        chdir: "~/WeightTrackerTst"

    - name: initialize db
      shell: npm run initdb
      args:
        chdir: "~/WeightTrackerTst"

    - name: clear process
      shell: pm2 delete all
      ignore_errors: yes

    - name: run application
      shell: pm2 start npm -- run dev && pm2 save && pm2 startup
      args:
        chdir: "~/WeightTrackerTst"

   