---
- name: Dev
  hosts: dev
  become: yes
  
  tasks:
  - name: Install "Git"
    apt:
      name: git
      state: latest

  - name: Update "NodeJS" deb
    ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

  - name: Install "NodeJS"
    apt:
      name: nodejs
      state: present
      
  - name: Install "pm2"
    shell: npm install pm2 -g

  - name: Download "App" from git
    ansible.builtin.git:
      repo: https://github.com/Eduardgur/WeightTrackerTst.git
      dest: "~/WeightTrackerTst"

  - name: Install node packages
    ansible.builtin.shell: npm install
    args:
      chdir: "~/WeightTrackerTst"

  - name: Initialize DB
    ansible.builtin.shell: npm run initdb
    args:
      chdir: "~/WeightTrackerTst"
      
  - name: clear process
    ansible.builtin.shell: pm2 delete all
    ignore_errors: yes

  - name: run application
    ansible.builtin.shell: pm2 start npm -- run dev && pm2 save && pm2 startup
    args:
      chdir: "~/WeightTrackerTst"

   